{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "hub.fullname" . }}
{{- $routePrefix := .Values.routePrefix }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    hub: {{ .Values.hubLabelValue | default .Release.Name | quote }}
    app: {{ template "ingress.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
  name: {{ template "ingress.fullname" . }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: "{{ $routePrefix }}"
            backend:
              serviceName: "{{ $serviceName }}"
              servicePort: {{ .Values.hub.port }}
    {{- end -}}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
{{- end }}
