{{- if eq true .Values.hub.persistentVolume.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "hub.fullname" . }}-shared
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{- .Values.hub.persistenVolume.size }}
  storageClassName: standard
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "hub.fullname" . }}-videos
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{- .Values.hub.persistenVolume.size }}
  storageClassName: standard
{{- end }}
